recode_accom <- function(x) {
    factor(case_when(x == "Buying with the help of a mortgage or loan"                          ~ "Privately owned (self)",
                     x == "Live rent-free (including rent-free in relative’s/friends property)" ~ "Other",
                     x == "Other"                                                               ~ "Other",
                     x == "Privately owned (family)"                                            ~ "Other",
                     x == "Privately owned (self)"                                              ~ "Privately owned (self)",
                     x == "Rented (local authority)"                                            ~ "Rent (social)",
                     x == "Rented (private sector)"                                             ~ "Rent (private, voluntary)",
                     x == "Rented (voluntary sector)"                                           ~ "Rent (private, voluntary)",
                     x == "Shared ownership"                                                    ~ "Other"),
           levels = c("Privately owned (self)",
                      "Rent (social)",
                      "Rent (private, voluntary)",
                      "Other"))
}

recode_relat <- function(x) {
    factor(case_when(
                     x == "Civil Partnership"                     ~ "Civil partnership, married, cohabiting, non-cohabiting",
                     x == "Divorced"                              ~ "Divorced, separated, widowed",
                     x == "In a relationship and co-habiting"     ~ "Civil partnership, married, cohabiting, non-cohabiting",
                     x == "In a relationship but not co-habiting" ~ "Civil partnership, married, cohabiting, non-cohabiting",
                     x == "Married"                               ~ "Civil partnership, married, cohabiting, non-cohabiting",
                     x == "Separated"                             ~ "Divorced, separated, widowed",
                     x == "Single"                                ~ "Single",
                     x == "Widowed"                               ~ "Divorced, separated, widowed"),
           levels = c("Single",
                      "Civil partnership, married, cohabiting, non-cohabiting",
                      "Divorced, separated, widowed"))
}

recode_ethnicity <- function(dat) {
    dat %>%
    mutate(ethnic_group = case_when(str_detect(ethnicity, "Mixed") ~ "Mixed",
                                    str_detect(ethnicity, "White") ~ "White",
                                    str_detect(ethnicity, "Black") ~ "Black",
                                    str_detect(ethnicity, "Asian") ~ "Asian",
                                    str_detect(ethnicity, "Other") ~ "Other",
                                    TRUE ~ NA_character_),
           ethnic_f = factor(ethnic_group,
                              levels = c("White", "Black", "Asian",
                                         "Mixed", "Other")))
}



swap_names <- function(d) {
    rename(d,
           login_id = `Login ID`,
           consent_1 = `Consent_1`,
           consent_2 = `Consent_2`,
           consent_3 = `Consent_3`,
           consent_4 = `Consent_4`,
           consent_5 = `Consent_5`,
           consent_6 = `Consent_6`,
           consent_7 = `Consent_7`,
           consent_8 = `Consent_8`,
           follow_4 = `Follow_4`,
           gender = `Role_1`,
           role = `Role_2`,
           age = `Role_3`,
           longitudinal = `Follow_1`,
           future = `Follow_6`,
           virology = `Testing_1`,
           postcode = `Q18`,
           relat = `Q19`,
           ethnicity = `Q20`,
           birth = `Q22`,
           accom = `Q23`,
           children = `Q24`,
           children_n = `Q25`,
           children_cohabit = `Q26`,
           children_age = `Q27`,
           dependents = `Q28`,
           keyworker_self = `Q29`,
           keyworker_household = `Q31`,
           return_work = `Covid_work_1`,
           return_work_location = `Covid_work_2`,
           workplace_adjust = `Covid_work_3`,
           remote_usual = `Covid_work_4`,
           remote_pandemic = `Covid_work_5`,
           remote_challenges = `Covid_work_6`,
           remote_resolved = `Covid_work_8`,
           remote_affect = `Covid_work_9`,
           clinical_role = `Q207`,
           clinical_contact = `Q208`,
           staff_role = `Work_sta_1`,
           staff_ft = `Work_sta_2`,
           staff_years = `Work_sta_3`,
           staff_contract = `Work_sta_4`,
           staff_pay = `Work_sta_5`,
           staff_special = `Work_staf_6`,
           staff_special_clear = `Work_sta_8_1`,
           staff_special_timely = `Work_sta_8_2`,
           student_prog = `Work_Stu_1`,
           student_ft = `Work_Stu_3`,
           student_length = `Work_Stu_4`,
           student_year = `Work_Stu_5`,
           student_comm = `Work_Stu_6`,
           student_funding = `Work_stu_7`,
           student_contact_1 = `Work_stu_9_1`,
           student_contact_2 = `Work_stu_9_2`,
           student_funding_impact = `Work_stu_10`,
           comms_fq = `Com_1`,
           comms_institutional = `Com_2_1`,
           comms_departmental = `Com_2_2`,
           comms_supervisor = `Com_2_3`,
           comms_confidence = `Com_2_4`,
           comms_comments = `Com_3`,
           covid_suspect_self = `covid_per_exp_11`,
           covid_test = `covid_per_exp_1`,
           covid_test_result = `covid_per_exp_2`,
           covid_phys_felt = `covid_per_exp_3`,
           covid_fever = `covid_per_exp_4`,
           covid_cough = `covid_per_exp_6_1`,
           covid_fatigue = `covid_per_exp_6_2`,
           covid_headache = `covid_per_exp_6_3`,
           covid_breath = `covid_per_exp_6_4`,
           covid_throat = `covid_per_exp_6_5`,
           covid_smell = `covid_per_exp_6_6`,
           covid_hoarse = `covid_per_exp_6_7`,
           covid_chest = `covid_per_exp_6_8`,
           covid_abdomen = `covid_per_exp_6_9`,
           covid_diarrhoea = `covid_per_exp_6_10`,
           covid_confuse = `covid_per_exp_6_11`,
           covid_meals = `covid_per_exp_6_12`,
           covid_hosp = `covid_per_exp_6_13`,
           covid_fatigue_sev = `covid_per_exp_7`,
           covid_breath_sev = `covid_per_exp_8`,
           covid_hosp_treat = `covid_per_exp_9`,
           sym_swallow = `Recent_sym_1_1`,
           sym_urine = `Recent_sym_1_2`,
           sym_hallucinate = `Recent_sym_1_3`,
           sym_dizzy = `Recent_sym_1_4`,
           sym_sleep = `Recent_sym_1_5`,
           sym_vision = `Recent_sym_1_6`,
           sym_delusion = `Recent_sym_1_7`,
           covid_contact = `covid_ind_1`,
           covid_suspect_other = `covid_ind_2`,
           covid_suspect_household = `covid_ind_3`,
           covid_suspect_care = `covid_ind_5`,
           isolation_status = `covid_ind_9`,
           isolation_reason = `covid_ind_10`,
           isolation_ever = `covid_ind_11`,
           isolation_days = `Q180`,
           school = `covid_life_1`,
           childcare = `covid_life_2`,
           relocation = `covid_life_4`,
           relocation_reason = `covid_life_5`,
           living_current = `covid_life_7`,
           commute = `covid_life_8`,
           commute_public = `covid_life_9`,
           service_need = `covid_life_11`,
           service_access = `covid_life_12`,
           service_avoid = `covid_life_13`,
           stress_question = `covid_life_14`,
           stress_employment = `covid_life_15_1`,
           stress_education = `covid_life_15_2`,
           stress_finance = `covid_life_15_3`,
           stress_information = `covid_life_15_4`,
           stress_separation = `covid_life_15_5`,
           positive_change = `covid_life_17`,
           positive_change_detail = `covid_life_18`,
           attitude_knowledge = `Covid_att_1_1`,
           attitude_threat_general = `Covid_att_1_2`,
           attitude_threat_self = `Covid_att_1_3`,
           attitude_preoccupy = `Covid_att_1_4`,
           attitude_proud = `Covid_att_1_5`,
           attitude_community = `Covid_att_1_6`,
           attitude_adherence = `Covid_att_2_1`,
           attitude_gvnt = `Covid_att_2_2`,
           attitude_health_service = `Covid_att_2_3`,
           attitude_essentials = `Covid_att_2_4`,
           diagnoses = `usual_1`,
           pregnant = `usual_3...150`,
           chronic_any = `usual_3...151`,
           heart_problem = `usual_5`,
           immunosuppress = `usual_6`,
           chronic_asthma = `usual_7_1`,
           chronic_kidney = `usual_7_2`,
           chronic_liver = `usual_7_3`,
           chronic_neuro = `usual_7_4`,
           chronic_diabetes = `usual_7_5`,
           chronic_hiv = `usual_7_6`,
           chronic_weight = `usual_7_7`,
           chronic_cancer = `usual_7_8`,
           chronic_asthma_treat = `usual_8`,
           chronic_kidney_treat = `usual_9`,
           chronic_diabetes_treat = `usual_10`,
           chronic_cancer_type = `usual_11`,
           chronic_other = `usual_12`,
           gad_item_1 = `Mental_1_1`,
           gad_item_2 = `Mental_1_2`,
           gad_item_3 = `Mental_1_3`,
           gad_item_4 = `Mental_1_4`,
           gad_item_5 = `Mental_1_5`,
           gad_item_6 = `Mental_1_6`,
           gad_item_7 = `Mental_1_7`,
           gad_usual = `Mental_2`,
           phq_item_1 = `Mental_3_1`,
           phq_item_2 = `Mental_3_2`,
           phq_item_3 = `Mental_3_3`,
           phq_item_4 = `Mental_3_4`,
           phq_item_5 = `Mental_3_5`,
           phq_item_6 = `Mental_3_6`,
           phq_item_7 = `Mental_3_7`,
           phq_item_8 = `Mental_3_8`,
           phq_item_9 = `Mental_3_9`,
           phq_usual = `Mental_4`,
           dsh_item_1 = `Q179_1`,
           dsh_item_2 = `Q179_2`,
           dsh_item_3 = `Q179_3`,
           general_health = `Mental_5`,
           whoqol_item_1 = `Mental_6`,
           whoqol_item_2 = `Mental_7`,
           loc_item_1 = `Mental_8_1`,
           loc_item_2 = `Mental_8_2`,
           loc_item_3 = `Mental_8_3`,
           loc_item_4 = `Mental_8_4`,
           pcl_item_1 = `Mental_9_1`,
           pcl_item_2 = `Mental_9_2`,
           pcl_item_3 = `Mental_9_3`,
           pcl_item_4 = `Mental_9_4`,
           pcl_item_5 = `Mental_9_5`,
           pcl_item_6 = `Mental_9_6`,
           audit_item_1 = `SA_2`,
           audit_item_2 = `Alc_3`,
           audit_item_3 = `Alc_4_1`,
           audit_item_4 = `Alc_4_2`,
           audit_item_5 = `Alc_4_3`,
           audit_item_6 = `Alc_4_4`,
           audit_item_7 = `Alc_4_5`,
           audit_item_8 = `Alc_4_6`,
           audit_item_9 = `Alc_5`,
           audit_item_10 = `Alc_6`,
           audit_usual = `Alc_7`,
           ucla_item_1 = `Q44_1`,
           ucla_item_2 = `Q44_2`,
           ucla_item_3 = `Q44_3`,
           ucla_item_4 = `Q44_4`,
           ucla_usual = `Q45`,
           smoke_current = `Life1`,
           smoke_usual = `Life2`,
           fatigue_item_1 = `Q204`,
           fatigue_item_2 = `Q205`,
           fatigue_item_3 = `Q206`,
           ess_screen = `Q49`,
           ess_item_1 = `Q50_1`,
           ess_item_2 = `Q50_2`,
           ess_item_3 = `Q50_3`,
           ess_item_4 = `Q50_4`,
           ess_item_5 = `Q50_5`,
           ess_item_6 = `Q50_6`,
           ess_item_7 = `Q50_7`,
           ess_item_8 = `Q50_8`,
           nmss_item_1 = `Neuro_1`,
           nmss_item_2 = `Neuro_2`,
           limb_item_1 = `Neuro_3`,
           limb_item_2 = `Neuro_4`,
           limb_item_3 = `Neuro_5`,
           limb_item_4 = `Neuro_6`,
           face_item_1 = `Neuro_7`,
           face_item_2 = `Neuro_8_1`,
           face_item_3 = `Neuro_8_2`,
           face_item_4 = `Neuro_8_3`,
           tin_item_1 = `Neuro_9`,
           tin_item_2 = `Neuro_10`,
           headache_item_1 = `Neuro_11`,
           headache_item_2 = `Neuro_12_4`,
           headache_item_3 = `Neuro_12_5`,
           headache_item_4 = `Neuro_12_6`,
           headache_item_5 = `Neuro_12_7`,
           headache_item_6 = `Neuro_12_8`,
           cq_item_1 = `Q41_1`,
           cq_item_2 = `Q41_2`,
           cq_item_3 = `Q41_3`,
           cq_item_4 = `Q41_4`,
           cq_usual = `Q42`,
           brs_item_1 = `Q43_1`,
           brs_item_2 = `Q43_2`,
           brs_item_3 = `Q43_3`,
           brs_item_4 = `Q43_4`,
           brs_item_5 = `Q43_5`,
           brs_item_6 = `Q43_6`,
           start_date = `StartDate`,
           end_date = `EndDate`,
           status = `Status`,
           ip = `IPAddress`,
           progress = `Progress`,
           duration = `Duration (in seconds)`,
           finished = `Finished`,
           recorded_date = `RecordedDate`,
           response_id = `ResponseId`,
           lastname = `RecipientLastName`,
           firstname = `RecipientFirstName`,
           email = `RecipientEmail`,
           extref = `ExternalReference`,
           lat = `LocationLatitude`,
           long = `LocationLongitude`,
           distrib = `DistributionChannel`,
           lang = `UserLanguage`,
           follow2 = `Follow_2`,
           follow3 = `Follow_3`,
           follow5 = `Follow_5`,
           testing2 = `Testing_2`,
           testing3 = `Testing_3`,
           testing4 = `Testing_4`,
           testing5 = `Testing_5`,
           final_1 = `Final_1`) 
}


